//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualShow3DLight.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualShow3DLight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplyShapeData {
            get {
                object obj = ResourceManager.GetObject("ApplyShapeData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileManagement64 {
            get {
                object obj = ResourceManager.GetObject("FileManagement64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.
        /// </summary>
        internal static string idsApplicationMenuBar {
            get {
                return ResourceManager.GetString("idsApplicationMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.
        /// </summary>
        internal static string idsApplicationName {
            get {
                return ResourceManager.GetString("idsApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.
        /// </summary>
        internal static string idsApplicationToolbar {
            get {
                return ResourceManager.GetString("idsApplicationToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ShareVisual.
        /// </summary>
        internal static string idsCompanyName {
            get {
                return ResourceManager.GetString("idsCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer le projet actif ?.
        /// </summary>
        internal static string idsConfirmDelete {
            get {
                return ResourceManager.GetString("idsConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.
        /// </summary>
        internal static string idsDefaultUser {
            get {
                return ResourceManager.GetString("idsDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;VisualShow3DLight : &quot;.
        /// </summary>
        internal static string idsDocumentTitle {
            get {
                return ResourceManager.GetString("idsDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de publication du document {0}.
        /// </summary>
        internal static string idsErrorPublish {
            get {
                return ResourceManager.GetString("idsErrorPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix du répertoire de la base de données.
        /// </summary>
        internal static string idsFdOpenTitleOptionPath {
            get {
                return ResourceManager.GetString("idsFdOpenTitleOptionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur ouverture fichier {0} .
        /// </summary>
        internal static string idsFileNotFound {
            get {
                return ResourceManager.GetString("idsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication.
        /// </summary>
        internal static string idsFolderNameDefaultValue {
            get {
                return ResourceManager.GetString("idsFolderNameDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder.
        /// </summary>
        internal static string idsFolderNameKey {
            get {
                return ResourceManager.GetString("idsFolderNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier d&apos;aide {0} introuvable.
        /// </summary>
        internal static string idsHelpfileNotFound {
            get {
                return ResourceManager.GetString("idsHelpfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le document actif n&apos;est pas un document VisualShow3DLight.
        /// </summary>
        internal static string idsInvalidDocumentType {
            get {
                return ResourceManager.GetString("idsInvalidDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande non implémentée.
        /// </summary>
        internal static string idsNotImplemented {
            get {
                return ResourceManager.GetString("idsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document actif nul !!!.
        /// </summary>
        internal static string idsNullActiveDoc {
            get {
                return ResourceManager.GetString("idsNullActiveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à visApp nul !!!.
        /// </summary>
        internal static string idsNullApp {
            get {
                return ResourceManager.GetString("idsNullApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à visDocument du VisualShow3DLight doc nul !!!.
        /// </summary>
        internal static string idsNullDoc {
            get {
                return ResourceManager.GetString("idsNullDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\Dev\VisualShow3DLight\VisualShow3DLight\Gabarits.
        /// </summary>
        internal static string idsStencilDefaultValue {
            get {
                return ResourceManager.GetString("idsStencilDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gabarits.
        /// </summary>
        internal static string idsStencilKey {
            get {
                return ResourceManager.GetString("idsStencilKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.vssx.
        /// </summary>
        internal static string idsStencilName {
            get {
                return ResourceManager.GetString("idsStencilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\Dev\VisualShow3DLight\VisualShow3DLight\System.
        /// </summary>
        internal static string idsSystemDefaultValue {
            get {
                return ResourceManager.GetString("idsSystemDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System.
        /// </summary>
        internal static string idsSystemKey {
            get {
                return ResourceManager.GetString("idsSystemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\Dev\VisualShow3DLight\VisualShow3DLight\Modeles.
        /// </summary>
        internal static string idsTemplateDefaultValue {
            get {
                return ResourceManager.GetString("idsTemplateDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modeles.
        /// </summary>
        internal static string idsTemplateKey {
            get {
                return ResourceManager.GetString("idsTemplateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VisualShow3DLight.vstx.
        /// </summary>
        internal static string idsTemplateName {
            get {
                return ResourceManager.GetString("idsTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.
        /// </summary>
        internal static string idsUserModeDefaultValue {
            get {
                return ResourceManager.GetString("idsUserModeDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UserMode.
        /// </summary>
        internal static string idsUserModeKey {
            get {
                return ResourceManager.GetString("idsUserModeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Panel3D32 {
            get {
                object obj = ResourceManager.GetObject("Panel3D32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectClose64 {
            get {
                object obj = ResourceManager.GetObject("ProjectClose64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectNew64 {
            get {
                object obj = ResourceManager.GetObject("ProjectNew64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectOpen64 {
            get {
                object obj = ResourceManager.GetObject("ProjectOpen64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectSave64 {
            get {
                object obj = ResourceManager.GetObject("ProjectSave64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectSaveAs64 {
            get {
                object obj = ResourceManager.GetObject("ProjectSaveAs64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateX {
            get {
                object obj = ResourceManager.GetObject("RotateX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateY {
            get {
                object obj = ResourceManager.GetObject("RotateY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateZ {
            get {
                object obj = ResourceManager.GetObject("RotateZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numérotation incorrecte, , la modification du numéro sera ignorée !!!.
        /// </summary>
        internal static string strBadNum {
            get {
                return ResourceManager.GetString("strBadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord ({0})|{1}.
        /// </summary>
        internal static string strCalculExtension {
            get {
                return ResourceManager.GetString("strCalculExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document ({0})|{1}.
        /// </summary>
        internal static string strDocExtension {
            get {
                return ResourceManager.GetString("strDocExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessin (*.vsdx;*.vsd;*.vdx)|*.vsdx;*.vsd;*.vdx.
        /// </summary>
        internal static string strFdFilterDrawing {
            get {
                return ResourceManager.GetString("strFdFilterDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image (*.png;*.bmp;*.gif)|*.png;*.bmp;*.gif.
        /// </summary>
        internal static string strFdLogoFilter {
            get {
                return ResourceManager.GetString("strFdLogoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connexion à la base de donnée de l&apos;application.
        /// </summary>
        internal static string strIdsDataBaseError {
            get {
                return ResourceManager.GetString("strIdsDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document introuvable  {0}, il ne peut être ouvert.
        /// </summary>
        internal static string strIdsDocumentNotfound {
            get {
                return ResourceManager.GetString("strIdsDocumentNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur {0}, {1}.
        /// </summary>
        internal static string strIdsErreurApp2 {
            get {
                return ResourceManager.GetString("strIdsErreurApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de projet invalide.
        /// </summary>
        internal static string strIdsErreurBadProjectName {
            get {
                return ResourceManager.GetString("strIdsErreurBadProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;initialiser le document {0} : {1}.
        /// </summary>
        internal static string strIdsErreurInitError {
            get {
                return ResourceManager.GetString("strIdsErreurInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer le dernier document du projet.
        /// </summary>
        internal static string strIdsErrorCannotDeleteLast {
            get {
                return ResourceManager.GetString("strIdsErrorCannotDeleteLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet introuvable.
        /// </summary>
        internal static string strIdsErrorProjectNotFound {
            get {
                return ResourceManager.GetString("strIdsErrorProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La saisie est trop longue elle sera traonquée à 255 caractères.
        /// </summary>
        internal static string strIdsErrorTruncated {
            get {
                return ResourceManager.GetString("strIdsErrorTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;enregistrement du projet {0}.
        /// </summary>
        internal static string strIdsErrorWhileSaving {
            get {
                return ResourceManager.GetString("strIdsErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;initialisation de l&apos;application {0}.
        /// </summary>
        internal static string strIdsInitializationError {
            get {
                return ResourceManager.GetString("strIdsInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur incorrecte.
        /// </summary>
        internal static string strIdsInvalidEntry {
            get {
                return ResourceManager.GetString("strIdsInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur maximale dépassée.
        /// </summary>
        internal static string strIdsInvalidLength {
            get {
                return ResourceManager.GetString("strIdsInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection de document invalide !.
        /// </summary>
        internal static string strIdsInvalidSelection {
            get {
                return ResourceManager.GetString("strIdsInvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection invalide.
        /// </summary>
        internal static string strIdsInvalidShapeSelection {
            get {
                return ResourceManager.GetString("strIdsInvalidShapeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet est déjà ouvert ou bien il a mal été fermé , voulez-vous forcer son ouverture ?.
        /// </summary>
        internal static string strIdsProjectAlreadyOpen {
            get {
                return ResourceManager.GetString("strIdsProjectAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les modifications effectuées sur la base de données ne seront prises en compte qu&apos;après le redémarrage de l&apos;application.
        /// </summary>
        internal static string strIdsQuitNeeded {
            get {
                return ResourceManager.GetString("strIdsQuitNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun projet actif.
        /// </summary>
        internal static string strNoActiveProject {
            get {
                return ResourceManager.GetString("strNoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun lien de navigation !!!.
        /// </summary>
        internal static string strNoNavigateLink {
            get {
                return ResourceManager.GetString("strNoNavigateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro existe déja, la modification sera ignorée !!!.
        /// </summary>
        internal static string strNumAlreadyExist {
            get {
                return ResourceManager.GetString("strNumAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet déja lié, opération impossible !!!.
        /// </summary>
        internal static string strObjectAlreadyLinked {
            get {
                return ResourceManager.GetString("strObjectAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La page : {0} existe déja.
        /// </summary>
        internal static string strPageAlreadyExist {
            get {
                return ResourceManager.GetString("strPageAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présentation ({0})|{1}.
        /// </summary>
        internal static string strPresentationExtension {
            get {
                return ResourceManager.GetString("strPresentationExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TranslateX {
            get {
                object obj = ResourceManager.GetObject("TranslateX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TranslateY {
            get {
                object obj = ResourceManager.GetObject("TranslateY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TranslateZ {
            get {
                object obj = ResourceManager.GetObject("TranslateZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vue3D32 {
            get {
                object obj = ResourceManager.GetObject("Vue3D32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
